#!/bin/bash

set -e -u

cd $(dirname $0)/..

export GO111MODULE=on

echo "getting dependencies..."
go mod download
go get -u github.com/onsi/ginkgo/ginkgo  # installs the ginkgo CLI
go get -u github.com/onsi/gomega/...

echo "running tests..."

ginkgo -r   "$@"