#!/bin/bash

#
# Copyright (c) 2019 LG Electronics Inc.
# SPDX-License-Identifier: Apache-2.0
#

set -e -u

export GO111MODULE=on

echo "getting dependencies..."
go get -u github.com/onsi/ginkgo/ginkgo  
go get -u github.com/onsi/gomega/...

echo "running tests..."

ginkgo -r   "$@"